name: Trigger Acme Demo Tests

on:
  push:
    branches:
      - 3.3.x

jobs:
  dispatch:
    name: Trigger tests in acme demo extension
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: iMattPro
          repo: phpbb-ext-acme-demo
          ref: testing-framework
          github_token: ${{ secrets.ACME_DEMO_PAT }}
          workflow_file_name: tests.yml
